name: Swift

on:
  pull_request:
    branches: [ main, develop ]

jobs:
  
  swiftLint:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Bundle
      run: bundle install
    - name: Run swiftlint
      run: bundle exec fastlane swiftLintLane

  build:
    needs: swiftLint
    env:
      DEVELOPER_DIR: /Applications/Xcode_13.0.app/Contents/Developer
    runs-on: macos-11.0
    steps:
    - uses: actions/checkout@v2
    - name: Install Bundle
      run: bundle install
    - name: Build
      run: bundle exec fastlane buildLane
    - name: Upload build
      uses: actions/upload-artifact@v2
      with:
        name: build
        path: '"derivedData/Build/Products/Debug CI-iphonesimulator/Addame.app"'
     
  unitTests:
    needs: build
    env:
      DEVELOPER_DIR: /Applications/Xcode_13.0.app/Contents/Developer
    runs-on: macos-11.0
    steps:
    - uses: actions/checkout@v2
    - name: Install Bundle
      run: bundle install
    - name: Run unit tests
      run: bundle exec fastlane unitTestLane
    - name: Run tests
      uses: actions/download-artifact@v2
      with:
        name: unitTests
        path: '"derivedData/Build/Products/Debug CI-iphonesimulator/EventFormViewTests.xctest"'

