name: SwiftTest

on:
  pull_request:
    branches: [ main, develop ]

jobs:
  Run_workspace_Tests:
    runs-on: macOS-latest
    steps:
    - name: Build and Test
      run: swift test
      env:
        DEVELOPER_DIR: /Applications/Xcode_11.4.app/Contents/Developer
